Repository kbrowngithub/Project1, pull requests merged in 2019-11, with the labels that each got.

#1 Bk change code folder
  assets/javascript/trains.js
  style.css
Labels: bug

#31 Added text in places for user clarity & fixed all breweries spelling, changed color of links and put an underline under each brewery result
  assets/css/style.css
  assets/javascript/app.js
  index.html
Labels: enhancement

#29 Events and Breweries links now open in new tab when clicked
  assets/javascript/app.js
Labels: enhancement

#32 Breweries with no website no longer refresh page
  assets/javascript/app.js
  diffs.txt
  index.html
Labels: bug fix

#36 Displays related images from Flickr below the main content
  assets/javascript/app.js
  index.html
Labels: bug fix, enhancement
